### ISSUE TITLE
Implement assist functions for local variables

### ISSUE THREAD

**Issue by happibum** [webida/webida-client#168]
- [x] webida/yatern#4 Find AST node for the variable at given position
- [x] webida/yatern#5 Find the same variable occurrences for given variable node
- [x] #284 When cursor is on a variable, highlight its occurrences
- [x] #169 Implement rename variables
- [x] #170 Implement multi-selection of variable occurrences 
- [x] #312 Enable/disable 'rename variable' menu item depending on the cursor position
- [ ] #311 Merge features for variable occurrences to webida master branch

**Comment by happibum** [comment]
Pending merge to webida master branch until editor's plugin system is ready.

**Comment by happibum** [comment]
The last issue #311 will be done in #536.
So I close this issue.
