### ISSUE TITLE
Implement auto-completion of property names

### ISSUE THREAD

**Issue by happibum** [webida/webida-client#171]
- [x] webida/yatern#6 Find possible property names of an expression
- [x] webida/yatern#9 Introduce a map from expressions to their AVals
- [x] #313 Implement yatern based auto-completion
